name: yan-zys
email: zhangyanshu@genomics.cn
active: true
research_interest:
  - bilaterian brain origin and evolution
  - cell type evolution
  - single-cell transcriptomics
  - comparative genomics
  - evolutionary genomics
  - nervous system evolution
  - neuron type homology

keywords:
  - brain evolution
  - cell type homology
  - independent origin hypothesis
  - common origin hypothesis
  - chimeric evolution

methods:
  - single-cell RNA sequencing
  - single-cell transcriptomic atlas construction
  - cross-species cell type homology comparison
  - ancestral cell type reconstruction
  - orthologous gene identification
  - transcription factor regulatory network comparison
  - SAMap
  - TranscriptFormer
  - MetaNeighbor


species:
  - Bilateria
  - tardigrade
  - velvet worm
  - ant
  - honeybee
  - fruit fly
  - planarian
  - annelid
  - octopus
  - amphioxus
  - zebrafish
  - bearded dragon
  - mouse

exclude:


